#!/bin/bash

# Coloring
NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

# Banner
clear
echo -e "${CYAN}▗▖ ▗▖ ▗▄▖ ▗▖    ▗▄▖ "
echo -e "${CYAN}▐▌▗▞▘▐▌ ▐▌▐▌   ▐▌ ▐▌"
echo -e "${WHITE}▐▛▚▖ ▐▛▀▜▌▐▌   ▐▛▀▜▌"
echo -e "${WHITE}▐▌ ▐▌▐▌ ▐▌▐▙▄▄▖▐▌ ▐▌"
echo -e "${RED}                  ${NOCOLOR}"
echo -e "        ${GREEN}@OFFICIAL_KALA_HACKER${NOCOLOR}"
echo
echo -e "-----------------------"

#!/bin/bash

# Color Definitions
NOCOLOR='\033[0m'
RED='\033[1;31m'        # Bright Red
GREEN='\033[1;32m'      # Bright Green
BLUE='\033[1;34m'       # Bright Blue
YELLOW='\033[0;33m'     # Yellow
PURPLE='\033[1;35m'     # Bright Purple
CYAN='\033[1;36m'       # Bright Cyan
WHITE='\033[1;37m'      # Bright White

# Function to display the banner
display_banner() {
    local banner_text="${1:-@OFFICIAL_KALA_HACKER}"  # Default text if none provided
    clear
    echo -e "${CYAN}▗▖ ▗▖ ▗▄▖ ▗▖    ▗▄▖ "
    echo -e "${CYAN}▐▌▗▞▘▐▌ ▐▌▐▌   ▐▌ ▐▌"
    echo -e "${PURPLE}▐▛▚▖ ▐▛▀▜▌▐▌   ▐▛▀▜▌"
    echo -e "${PURPLE}▐▌ ▐▌▐▌ ▐▌▐▙▄▄▖▐▌ ▐▌"
    echo -e "${YELLOW}                  ${NOCOLOR}"  # Change this line to yellow
    echo -e "        ${GREEN}${banner_text}${NOCOLOR}"
    echo
    echo -e "-----------------------"
